Controllers test
kensteph/blog pull request #6
Opened 2023-05-11 01:31 UTC by kensteph

In this PR I:
- Created a Request spec file for all controllers.
- Checked response for action:
  - If the response status was correct.
  - If a correct template was rendered.
  - If the response body includes correct placeholder text.

2023-05-11 01:40 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @kensteph, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 01:40 UTC, anagudelogu commented on spec/requests/posts_spec.rb
> +  end
- [ ] You did a great job working on this milestone! 💯 However, please make sure to include a test for the `response.body` containing the correct placeholder text. According to the requirements:

![image](https://github.com/quavo19/social-blog/assets/77069011/64f24e44-e2e8-46c3-8884-10f5c23c4ea7)

```rb
# Example
it 'response body includes the correct content' do
  get user_posts_path(user)
  expect(response.body).to match(/posts index/)
end
```


Please consider including this! 🤓 🔧

2023-05-11 01:40 UTC, anagudelogu commented on spec/requests/posts_spec.rb
> +  end
- [ ] Here happens the same, please make sure to include a test for the `response.body` containing the correct placeholder text. 🤓 🔧

2023-05-11 01:40 UTC, anagudelogu commented on spec/requests/users_spec.rb
> +  end
- [ ] Here happens the same, please make sure to include a test for the `response.body` containing the correct placeholder text. 🤓 🔧

2023-05-11 01:40 UTC, anagudelogu commented on spec/requests/users_spec.rb
> +  end
- [ ] Here happens the same, please make sure to include a test for the `response.body` containing the correct placeholder text. 🤓 🔧

2023-05-13 03:59 UTC, Davidosky007 approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed 
* Well written PR 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 04:09 UTC, merged